// ⚠️  Auto-generated by bini-router — do not edit.
// @ts-nocheck
// oxlint-disable
// oxfmt-ignore

import React, { Suspense } from 'react';
import { BrowserRouter, Routes, Route, Outlet, useLocation, useParams } from 'react-router-dom';

import Layout0 from './app/layout';

const Page0 = React.lazy(() => import('./app/page'));
const Page1 = React.lazy(() => import('./app/docs/page'));
const Page2 = React.lazy(() => import('./app/plugins/page'));
const Page3 = React.lazy(() => import('./app/docs/css'));
const Page4 = React.lazy(() => import('./app/showcase/page'));
const Page5 = React.lazy(() => import('./app/docs/load'));
const Page6 = React.lazy(() => import('./app/docs/icons'));
const Page7 = React.lazy(() => import('./app/docs/env-api'));
const Page8 = React.lazy(() => import('./app/docs/hosting'));
const Page9 = React.lazy(() => import('./app/docs/api-cors'));
const Page10 = React.lazy(() => import('./app/docs/api-hono'));
const Page11 = React.lazy(() => import('./app/docs/defaults'));
const Page12 = React.lazy(() => import('./app/docs/metadata'));
const Page13 = React.lazy(() => import('./app/docs/notfound'));
const Page14 = React.lazy(() => import('./app/docs/tailwind'));
const Page15 = React.lazy(() => import('./app/docs/api-plain'));
const Page16 = React.lazy(() => import('./app/docs/deploying'));
const Page17 = React.lazy(() => import('./app/docs/templates'));
const Page18 = React.lazy(() => import('./app/docs/api-routes'));
const Page19 = React.lazy(() => import('./app/docs/og-twitter'));
const Page20 = React.lazy(() => import('./app/docs/api-dynamic'));
const Page21 = React.lazy(() => import('./app/docs/css-modules'));
const Page22 = React.lazy(() => import('./app/plugins/bini-env'));
const Page23 = React.lazy(() => import('./app/plugins/bini-ssg'));
const Page24 = React.lazy(() => import('./app/docs/env-prefixes'));
const Page25 = React.lazy(() => import('./app/docs/installation'));
const Page26 = React.lazy(() => import('./app/docs/mdx-markdown'));
const Page27 = React.lazy(() => import('./app/docs/platform-ios'));
const Page28 = React.lazy(() => import('./app/docs/platform-web'));
const Page29 = React.lazy(() => import('./app/docs/static-export'));
const Page30 = React.lazy(() => import('./app/docs/dynamic-routes'));
const Page31 = React.lazy(() => import('./app/docs/platform-linux'));
const Page32 = React.lazy(() => import('./app/docs/platform-macos'));
const Page33 = React.lazy(() => import('./app/plugins/bini-deploy'));
const Page34 = React.lazy(() => import('./app/plugins/bini-native'));
const Page35 = React.lazy(() => import('./app/plugins/bini-router'));
const Page36 = React.lazy(() => import('./app/plugins/bini-server'));
const Page37 = React.lazy(() => import('./app/docs/parallel-routes'));
const Page38 = React.lazy(() => import('./app/plugins/bini-overlay'));
const Page39 = React.lazy(() => import('./app/docs/catch-all-routes'));
const Page40 = React.lazy(() => import('./app/docs/error-boundaries'));
const Page41 = React.lazy(() => import('./app/docs/platform-android'));
const Page42 = React.lazy(() => import('./app/docs/platform-windows'));
const Page43 = React.lazy(() => import('./app/docs/layouts-and-pages'));
const Page44 = React.lazy(() => import('./app/docs/production-server'));
const Page45 = React.lazy(() => import('./app/docs/project-structure'));
const Page46 = React.lazy(() => import('./app/docs/file-based-routing'));
const Page47 = React.lazy(() => import('./app/plugins/create-bini-app'));
const Page48 = React.lazy(() => import('./app/docs/folder-based-routing'));
const Page49 = React.lazy(() => import('./app/docs/environment-variables'));
const Page50 = React.lazy(() => import('./app/docs/linking-and-navigating'));

// ─── Error Boundary ───────────────────────────────────────────────────────────

class ErrorBoundary extends React.Component<
  { children: React.ReactNode; fallback?: React.ComponentType<{ error: Error; reset: () => void }>; resetKey?: string },
  { error: Error | null }
> {
  constructor(props: { children: React.ReactNode; fallback?: React.ComponentType<{ error: Error; reset: () => void }>; resetKey?: string }) {
    super(props);
    this.state = { error: null };
  }
  static getDerivedStateFromError(error: Error) { return { error }; }
  componentDidUpdate(prev: { resetKey?: string }) {
    if (this.state.error && prev.resetKey !== this.props.resetKey) {
      this.setState({ error: null });
    }
  }
  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    if (import.meta.env.DEV) {
      window.dispatchEvent(new CustomEvent('__bini_error__', {
        detail: { name: error.name, message: error.message, stack: error.stack, componentStack: errorInfo.componentStack, _type: 'runtime' }
      }));
    }
  }
  override render() {
    if (this.state.error) {
      const reset = () => this.setState({ error: null });
      if (this.props.fallback) {
        const Fallback = this.props.fallback;
        return <Fallback error={this.state.error} reset={reset} />;
      }
      if (import.meta.env.DEV) return null;
      return <DefaultError error={this.state.error} reset={reset} />;
    }
    return this.props.children;
  }
}


function WithParams({ layout: Layout, children }: { layout: React.ComponentType<any>; children: React.ReactNode }) {
  const params = useParams();
  return <Layout params={params}>{children}</Layout>;
}




function Spinner() {
  const [isDark, setIsDark] = React.useState(false);
  React.useEffect(() => {
    const isDarkMode = document.documentElement.classList.contains('dark') ||
      window.matchMedia('(prefers-color-scheme: dark)').matches;
    setIsDark(isDarkMode);
    const observer = new MutationObserver(() => {
      setIsDark(document.documentElement.classList.contains('dark'));
    });
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
    return () => observer.disconnect();
  }, []);
  const styles = {
    root: { margin: 0, padding: 0, minHeight: '100vh', width: '100%' },
    container: {
      minHeight: '100vh', width: '100%', display: 'flex',
      alignItems: 'center', justifyContent: 'center',
      backgroundColor: isDark ? '#000000' : '#ffffff', margin: 0, padding: 0,
    },
    spinnerWrapper: { position: 'relative', width: '3rem', height: '3rem' },
    outerRing: {
      position: 'absolute', inset: 0, borderRadius: '9999px',
      border: '4px solid', borderColor: isDark ? '#262626' : '#e5e5e5',
    },
    spinningRing: {
      position: 'absolute', inset: 0, borderRadius: '9999px',
      border: '4px solid', borderTopColor: 'transparent',
      borderRightColor: 'transparent', borderBottomColor: 'transparent',
      borderLeftColor: '#06b6d4', animation: 'spin 0.8s linear infinite',
    },
  };
  return (
    <div style={styles.root}>
      <div style={styles.container}>
        <div style={styles.spinnerWrapper}>
          <div style={styles.outerRing} />
          <div style={styles.spinningRing} />
        </div>
      </div>
      <style>{`
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { margin: 0; padding: 0; }
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
      `}</style>
    </div>
  );
}


function DefaultError({ error, reset }) {
  const [isDark, setIsDark] = React.useState(false);
  const homeHref = (typeof basename === 'string' && basename !== '/' && basename !== '.') ? basename : '/';
  React.useEffect(() => {
    const isDarkMode = document.documentElement.classList.contains('dark') ||
      window.matchMedia('(prefers-color-scheme: dark)').matches;
    setIsDark(isDarkMode);
    const observer = new MutationObserver(() => {
      setIsDark(document.documentElement.classList.contains('dark'));
    });
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
    return () => observer.disconnect();
  }, []);
  const styles = {
    root: { margin: 0, padding: 0, minHeight: '100vh', width: '100%' },
    container: {
      minHeight: '100vh', width: '100%', display: 'flex', flexDirection: 'column',
      alignItems: 'center', justifyContent: 'center', textAlign: 'center',
      padding: '2rem', backgroundColor: isDark ? '#000000' : '#ffffff',
      fontFamily: 'system-ui, -apple-system, sans-serif', margin: 0,
    },
    wrapper: { maxWidth: '28rem', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '1.5rem', alignItems: 'center' },
    word: {
      fontSize: '4.5rem', fontWeight: 'bold', lineHeight: 1, letterSpacing: '-0.025em',
      background: 'linear-gradient(135deg, #06b6d4, #3b82f6)',
      WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent',
    },
    title: { fontSize: '1.5rem', fontWeight: 600, color: isDark ? '#ffffff' : '#000000' },
    message: { color: isDark ? '#a3a3a3' : '#737373', maxWidth: '24rem', margin: '0 auto' },
    errorBox: {
      textAlign: 'left', width: '100%', fontSize: '0.75rem',
      color: isDark ? '#f87171' : '#dc2626',
      background: isDark ? 'rgba(127, 29, 29, 0.2)' : '#fef2f2',
      border: '1px solid ' + (isDark ? 'rgba(127, 29, 29, 0.5)' : '#fecaca'),
      borderRadius: '0.5rem', padding: '0.75rem', overflow: 'auto',
      maxHeight: '10rem', margin: 0,
      fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    },
    buttonRow: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.75rem', flexWrap: 'wrap' },
    button: {
      display: 'inline-block', padding: '0.75rem 2rem', borderRadius: '0.5rem',
      background: 'linear-gradient(135deg, #06b6d4, #3b82f6)', color: 'white',
      textDecoration: 'none', fontSize: '0.875rem', fontWeight: 500,
      transition: 'opacity 0.2s', cursor: 'pointer', border: 'none', fontFamily: 'inherit',
    },
    secondaryButton: {
      display: 'inline-block', padding: '0.75rem 2rem', borderRadius: '0.5rem',
      background: isDark ? '#171717' : '#f5f5f5', color: isDark ? '#ffffff' : '#000000',
      textDecoration: 'none', fontSize: '0.875rem', fontWeight: 500,
      transition: 'background 0.2s', cursor: 'pointer', border: 'none', fontFamily: 'inherit',
    },
  };
  return (
    <div style={styles.root}>
      <div style={styles.container}>
        <div style={styles.wrapper}>
          <div style={styles.word}>OOPS</div>
          <h1 style={styles.title}>Something went wrong</h1>
          <p style={styles.message}>
            An unexpected error occurred while loading this page. You can try
            again, or head back to the home page.
          </p>
          {import.meta.env.DEV && error && error.message && (
            <pre style={styles.errorBox}>{error.message}</pre>
          )}
          <div style={styles.buttonRow}>
            <button type="button" onClick={reset} style={styles.button}>Try again</button>
            <a href={homeHref} style={styles.secondaryButton}>← Back to home</a>
          </div>
        </div>
      </div>
      <style>{`
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { margin: 0; padding: 0; }
        a { text-decoration: none; }
      `}</style>
    </div>
  );
}




const INITIAL_TITLE = typeof document !== 'undefined' ? document.title : '';
function TitleSetter({ title }: { title: string | null }) {
  React.useEffect(() => {
    if (typeof document !== 'undefined') {
      document.title = title ?? INITIAL_TITLE;
    }
  }, [title]);
  return null;
}


function Default404() {
  const [isDark, setIsDark] = React.useState(false);
  const homeHref = (typeof basename === 'string' && basename !== '/' && basename !== '.') ? basename : '/';
  React.useEffect(() => {
    const isDarkMode = document.documentElement.classList.contains('dark') ||
      window.matchMedia('(prefers-color-scheme: dark)').matches;
    setIsDark(isDarkMode);
    const observer = new MutationObserver(() => {
      setIsDark(document.documentElement.classList.contains('dark'));
    });
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
    return () => observer.disconnect();
  }, []);
  const styles = {
    root: { margin: 0, padding: 0, minHeight: '100vh', width: '100%' },
    container: {
      minHeight: '100vh', width: '100%', display: 'flex',
      flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
      textAlign: 'center', padding: '2rem',
      backgroundColor: isDark ? '#000000' : '#ffffff',
      fontFamily: 'system-ui, -apple-system, sans-serif', margin: 0,
    },
    wrapper: { maxWidth: '42rem', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '1.5rem' },
    number: {
      fontSize: '8rem', fontWeight: 'bold', lineHeight: 1, letterSpacing: '-0.025em',
      background: 'linear-gradient(135deg, #06b6d4, #3b82f6)',
      WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent',
    },
    title: { fontSize: '1.5rem', fontWeight: 600, color: isDark ? '#ffffff' : '#000000' },
    message: { color: isDark ? '#a3a3a3' : '#737373', maxWidth: '28rem', margin: '0 auto' },
    button: {
      display: 'inline-block', padding: '0.75rem 2rem', borderRadius: '0.5rem',
      background: 'linear-gradient(135deg, #06b6d4, #3b82f6)', color: 'white',
      textDecoration: 'none', fontSize: '0.875rem', fontWeight: 500,
      transition: 'opacity 0.2s', cursor: 'pointer', border: 'none',
    },
  };
  return (
    <div style={styles.root}>
      <div style={styles.container}>
        <div style={styles.wrapper}>
          <div style={styles.number}>404</div>
          <h1 style={styles.title}>Page not found</h1>
          <p style={styles.message}>The page you're looking for doesn't exist or has been moved.</p>
          <div><a href={homeHref} style={styles.button}>← Back to home</a></div>
        </div>
      </div>
      <style>{`
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { margin: 0; padding: 0; }
        a { text-decoration: none; }
      `}</style>
    </div>
  );
}

// ─── SlotMatch context (no-op if no parallel routes) ─────────────────────────
const SlotMatchContext = React.createContext({ slot: '', matched: false, setMatched: () => {} });

// ─── Last-resort boundary ─────────────────────────────────────────────────────
class LastResortBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { error: null };
  }
  static getDerivedStateFromError(error) {
    return { error };
  }
  render() {
    if (this.state.error) {
      return React.createElement(
        'div',
        {
          style: {
            minHeight: '100vh',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '2rem',
            fontFamily: 'system-ui, -apple-system, sans-serif',
            textAlign: 'center',
          },
        },
        React.createElement('h1', { style: { fontSize: '1.5rem', marginBottom: '1rem' } }, 'Something went wrong'),
        React.createElement(
          'pre',
          {
            style: {
              fontSize: '0.75rem',
              maxWidth: '40rem',
              overflow: 'auto',
              padding: '0.75rem',
              border: '1px solid #ddd',
              borderRadius: '0.5rem',
              background: '#f9f9f9',
              textAlign: 'left',
            },
          },
          String((this.state.error && this.state.error.message) || this.state.error),
        ),
        React.createElement(
          'button',
          {
            type: 'button',
            onClick: () => this.setState({ error: null }),
            style: {
              marginTop: '1rem',
              padding: '0.75rem 2rem',
              borderRadius: '0.5rem',
              border: 'none',
              background: '#06b6d4',
              color: 'white',
              cursor: 'pointer',
            },
          },
          'Try again',
        ),
      );
    }
    return this.props.children;
  }
}

export function AppRoutes() {
  const location = useLocation();
  return (
    <Routes>
        <Route element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><WithParams layout={Layout0}><Outlet /></WithParams></ErrorBoundary></Suspense>}>
          <Route path="/" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page0 /></ErrorBoundary></Suspense>} />
          <Route path="/docs" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page1 /></ErrorBoundary></Suspense>} />
          <Route path="/plugins" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page2 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/css" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page3 /></ErrorBoundary></Suspense>} />
          <Route path="/showcase" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page4 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/load" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page5 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/icons" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page6 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/env-api" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page7 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/hosting" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page8 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/api-cors" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page9 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/api-hono" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page10 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/defaults" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page11 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/metadata" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page12 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/notfound" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page13 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/tailwind" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page14 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/api-plain" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page15 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/deploying" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page16 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/templates" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page17 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/api-routes" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page18 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/og-twitter" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page19 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/api-dynamic" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page20 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/css-modules" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page21 /></ErrorBoundary></Suspense>} />
          <Route path="/plugins/bini-env" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page22 /></ErrorBoundary></Suspense>} />
          <Route path="/plugins/bini-ssg" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page23 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/env-prefixes" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page24 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/installation" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page25 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/mdx-markdown" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page26 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/platform-ios" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page27 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/platform-web" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page28 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/static-export" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page29 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/dynamic-routes" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page30 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/platform-linux" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page31 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/platform-macos" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page32 /></ErrorBoundary></Suspense>} />
          <Route path="/plugins/bini-deploy" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page33 /></ErrorBoundary></Suspense>} />
          <Route path="/plugins/bini-native" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page34 /></ErrorBoundary></Suspense>} />
          <Route path="/plugins/bini-router" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page35 /></ErrorBoundary></Suspense>} />
          <Route path="/plugins/bini-server" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page36 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/parallel-routes" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page37 /></ErrorBoundary></Suspense>} />
          <Route path="/plugins/bini-overlay" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page38 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/catch-all-routes" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page39 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/error-boundaries" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page40 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/platform-android" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page41 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/platform-windows" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page42 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/layouts-and-pages" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page43 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/production-server" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page44 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/project-structure" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page45 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/file-based-routing" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page46 /></ErrorBoundary></Suspense>} />
          <Route path="/plugins/create-bini-app" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page47 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/folder-based-routing" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page48 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/environment-variables" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page49 /></ErrorBoundary></Suspense>} />
          <Route path="/docs/linking-and-navigating" element={<Suspense fallback={<Spinner />}><ErrorBoundary resetKey={location.pathname}><TitleSetter title={"React for Cross-Platform"} /><Page50 /></ErrorBoundary></Suspense>} />
        </Route>

        <Route path="*" element={<Default404 />} />
    </Routes>
  );
}

export const basename = "/";

function OuterBoundary({ children }) {
  const location = useLocation();
  return (
    <ErrorBoundary fallback={DefaultError} resetKey={location.pathname}>
      {children}
    </ErrorBoundary>
  );
}

export default function App() {
  return (
    <LastResortBoundary>
      <BrowserRouter basename={basename}>
        <OuterBoundary>
          <AppRoutes />
        </OuterBoundary>
      </BrowserRouter>
    </LastResortBoundary>
  );
}
